nelmio_api_doc:
    documentation:
        info:
            title: Battle Ship
            description: Use this API to play a Battle Ship Game
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc) # Accepts routes under /api except /api/doc
