framework:
  workflows:
    battle_ship:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
        property: state
      supports:
        - App\Entity\Battle
      initial_marking: waiting
      places:
        - waiting
        - ready
        - playing
        - finished
      transitions:
        set_options:
          from: waiting
          to: ready
        set_players:
          from: ready
          to:   playing
        finish:
          from: [playing]
          to:   finished
    player_shoot:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
        property: state
      supports:
        - App\Entity\Player
      initial_marking: ducking
      places:
        - ducking
        - shooting
        - won
      transitions:
        shoot:
          from: shooting
          to: ducking
        duck:
          from: ducking
          to: shooting
        win:
          from: [ducking, shooting]
          to: won
