framework:
  workflows:
    battle_ship:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
        property: currentState
      supports:
        - App\Entity\Battle
      initial_marking: waiting
      places:
        - waiting
        - ready
        - started
        - finished
      transitions:
        set-options:
          from: waiting
          to: ready
        place-ships:
          from: ready
          to:   started
        finish:
          from: [started]
          to:   finished
