framework:
  workflows:
    battle_ship:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
        property: currentState
      supports:
        - App\Entity\Battle
      initial_marking: start
      places:
        - start
        - started
        - finished
      transitions:
        place:
          from: start
          to:   started
        finish:
          from: [started]
          to:   finished
