- name: Set up application
  hosts: localhost
  connection: local
  tasks:
    - name: Install dependencies
      pip:
        name:
          - docker
          - docker-compose
    - name: Start Application with docker compose up
      docker_compose:
        project_src: ../../
        build: yes
    - name: Install dependencies
      command: docker-compose run --rm app install --no-interaction
      args:
        chdir: ../../
