- name: Set up application
  hosts: localhost
  connection: local
  tasks:
    - name: Define hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 api.battle.local"
        state: present
    - name: Define env file
      template:
        src: ../../.env.dist
        dest: ../../.env
        force: no
    - name: Adjust Web Port in the .env file
      lineinfile:
        path: ../../.env
        regexp: '^PORT_WEB='
        line: "PORT_WEB={{ web_port }}"
        backrefs: yes
